language: scala
scala:
  - 2.12.1 
  - 2.11.8
jdk: oraclejdk8
cache:
  directories:
   - ~/.ivy2
   - ~/.sbt
script:
  - sbt clean test coverageReport &&
    sbt coverageAggregate
after_success:
  - sbt coveralls
