name: extruder
baseurl: /extruder
description: Populate Scala case classes from any any configuration source
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.5.1-SNAPSHOT
org: extruder
markdown: kramdown
