name: extruder
baseurl: /extruder
description: Populate Scala case classes from any data source
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.10.1-4-61033806-SNAPSHOT
org: io.extruder
markdown: kramdown
