name: extruder
baseurl: /extruder
description: Populate Scala case classes from any data source
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.11.0
org: io.extruder
markdown: kramdown
